[package]
name = "my-zk-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bls12-381 = "0.6.0"
ark-ec = "0.6.0"
ark-ff = "0.6.0"
ark-serialize = "0.6.0"
ark-std = "0.6.0"
ark-test-curves = "0.6.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
sha2 = "0.10.9"
zeroize = "1.8.2"

[features]
ark-asm = ["ark-ff/asm"]

[dev-dependencies]
ark-bls12-381 = "0.6.0"
ark-bn254 = "0.6.0"
ark-pallas = "0.6.0"
ark-poly = "0.6.0"
criterion = "0.7.0"

[[bench]]
name = "fp_vs_ark"
harness = false

[[bench]]
name = "poly_vs_ark"
harness = false
